### ISSUE TITLE
Unable to connect with Bluetooth transport to SDL Core

### ISSUE THREAD

**Issue by kostyaBoss** [smartdevicelink/sdl_java_suite#1650] opened 2021-03-30 19:37 UTC
### Bug Report
Unable to connect with Bluetooth transport to SDL Core

##### Reproduction Steps
1. Turn bluetooth off on phone.
2. Install Hello SDL and ensure it is the only SDL app installed.
3. Make sure to clear all the app data for Hello SDL under settings.
4. Turn on bluetooth on phone.
5. Allow BT to connect (A2DP); pair with SDL Core if necessary.
6. Observe through logs that the SDL Device Listener has started and is currently listening on an RFCOMM channel.

##### Expected Behavior
HelloSDL mobile application successfully connected to SDL Core

##### Observed Behavior
HelloSDL mobile application doesn't connect to SDL Core, bluetooth restart doesn't help to solve the issue

##### OS & Version Information
Android Version: 9, 10
Android devices:
1. Xiaomi Redmi Note 5, Android version 9, MIUI
2. Nokia 7.1, Android version 9, clean Android
3. Xiaomi Redmi Note 9, Android version 10, MIUI

SDL Android Version: latest develop (26.03.2021), [commit](https://github.com/smartdevicelink/sdl_java_suite/commit/98fc5004fb10aee476d73057b67eadf1b1204e6c "commit")

**Laptop**:
Lenovo Thinkpad, Ubuntu 18.04
**SdlCore versions tested against:**
release/7.1.0-RC1 [core](https://github.com/smartdevicelink/sdl_core/commit/40cf3dc7afdab7384c7a0f43336c7a88665db240 "core")
release/7.0.0 [core](https://github.com/smartdevicelink/sdl_core/tree/7.0.0 "core")
release/6.1.1 [core](https://github.com/smartdevicelink/sdl_core/tree/6.1.1 "core")

[TransportManager.log](https://github.com/smartdevicelink/sdl_java_suite/files/6231740/TransportManager.log)
[SmartDeviceLinkCore.log](https://github.com/smartdevicelink/sdl_java_suite/files/6231742/SmartDeviceLinkCore.log)
[logcat.log](https://github.com/smartdevicelink/sdl_java_suite/files/6231743/logcat.log)

**Comment by joeygrover** [comment] 2021-03-30 20:56
We just retested to be sure and confirmed everything works as expected; unless new information is provided this issue will be closed as it is not reproducible. 

We regularly test bluetooth connections between the SDL Android library and the SDL Core project. All the listed versions of Core have had those tests performed and they work as expected with the SDL Android library.

It is important to know that the library is listening for an incoming bluetooth connection. It does not actively reach out to Core to create the connection, but the exact opposite.

Core's code will search for all available bluetooth devices and do an SDP query on all of them. This is a time consuming process and can lead to some errors (especially if there are multiple bluetooth devices present). It can also take some time for the connection to actually happen. 

I recommend possibly checking out [this PR](https://github.com/smartdevicelink/sdl_core/pull/3425) that shows how to disable SDL Core from searching unpaired devices. Then make sure only the phone is paired with the device.

**Comment by joeygrover** [comment] 2021-03-31 16:04
We have verified with multiple machines and setups that the two projects connect as expected. The transport code hasn't been really modified on Core for a long time so everything should continue to work as expected. The additional information you can supply is as followed:

1. What was the last version of the Java Suite library that you were able to get a successful bluetooth connection to Core with?
2. What was the last version of SDL Core you've gotten a successful bluetooth connection with the Java Suite library?
3. Are you using a VM? If so,
    1. What OS are you using for your VM?
    2. What OS are you using to host your VM
4. If not, what OS are you using?
5. Are you using the built in bluetooth adapter?
6. Are you using a bluetooth dongle? What dongle?
7. Are you able to perform an SDP query from the machine through the command line? (without Core)
8. Have you tried testing without the code that scans for ALL devices regardless of pair status?
9. Do you have any other Android devices? Specifically from the Pixel line?


While the BlueZ stack is not exactly production ready, it is more than capable of connecting with an Android device and as previously stated we have not encountered an issue that exists because of either project's code. This might be a better slack conversation to help you debug your particular situation as I do not believe this is an actual issue with the repo, but rather that of the setup.

**Comment by a-prykho** [comment] 2021-04-01 10:26
`1. What was the last version of the Java Suite library that you were able to get a successful bluetooth connection to Core with?`

We have checked with the versions from master and develop branches of Java Suite library . 
We`ve got 1 successful connection for more than 10 unsuccessful ones.

`2. What was the last version of SDL Core you've gotten a successful bluetooth connection with the Java Suite library?`

We checked with the SDL Core versions 6.1, 7.0, 7.1. 
We got 1 successful connection for more than 10 unsuccessful ones for each SDL Core versions.

`3. Are you using a VM?`
No

`4. If not, what OS are you using?`
Ubuntu 18.04

`5. Are you using the built in bluetooth adapter?`
Yes

`6. Are you using a bluetooth dongle? What dongle?`
No

`7. Are you able to perform an SDP query from the machine through the command line? (without Core)`
Yes

`8. Have you tried testing without the code that scans for ALL devices regardless of pair status?`

We`ve tested with only one paired phone

` 9. Do you have any other Android devices? Specifically from the Pixel line?`
We used for testing:
1) Xiaomi Redmi Note 5, Android v. 9
2) Nokia 7.1, Android v. 9, clean Android
3) Xiaomi Redmi Note 9, Android v. 10
4) Samsung Galaxy M21; Android v.10
5) Samsung Galaxy Fold SI; Android v.10

**Comment by joeygrover** [comment] 2021-04-16 15:53
Closing this issue as not a bug. The project maintainer worked with the author and company offline and solved their issue.

**Closed by joeygrover** 2021-04-16 15:53 UTC
