### ISSUE TITLE
[Consultation] About SDL crash (Android)

### ISSUE THREAD

**Issue by first-moisture** [smartdevicelink/sdl_java_suite#1184] opened 2019-10-01 01:53 UTC
[Delete any non-applicable sections, but we may ask for more information. Please reference the [SmartDeviceLink GitHub Best Practices](https://d83tozu1c8tt6.cloudfront.net/media/resources/SDL_GitHub_BestPractices.pdf) for further instructions on how to enter an issue.]

### Bug Report
【background】
Recently, I have been troubled by an increase in SDL crashes for the service I am in charge of.

【the purpose】
I want to know how to fix this SDL crash as soon as possible.
I want to borrow your wisdom.

[Details]
There is log data downloaded from Fabric.
* ■■■：Company name of the app
* ●●●●●●●：App service name

##### Reproduction Steps
The daily Fabric SDL data (crash) is high.
[crash.pdf](https://github.com/smartdevicelink/sdl_java_suite/files/3674043/crash.pdf)

##### Expected Behavior
Reduce SDL crashes

##### Observed Behavior
[Some observed behavior]

##### OS & Version Information
* Android Version: 9
* SDL Android Version: 4.5
* Testing Against: 

##### Test Case, Sample Code, and / or Example App
[Paste a link to a PR, gist, or other code that exemplifies this behavior]

**Comment by joeygrover** [comment] 2019-10-01 03:06
Thank you for submitting your first issue! In the future these issues should be created for specific issues on the library, not a request to look through logs and find any issue.

Since this is your first post I went ahead and looked at the logs. Based on the library version and the crash I can say this does not exist in the latest release of the library. Please update your library you are using. Also make sure you are following the latest guides exactly. I'm guessing the app doesn't include the metadata tags that are required now. 

I am closing the issue as the issue is not a current issue of the library.

**Closed by joeygrover** 2019-10-01 03:06 UTC

**Comment by first-moisture** [comment] 2019-10-01 05:09
@joeygrover -san,

Thank you for your comment.

I understand that our Ver.4.5 is low, but the crash increased more rapidly than 9/15 even though we did nothing.
Can you confirm this cause from the log data?
