### ISSUE TITLE
Crash when video streaming is started about 10 minutes if the WiFi signal is extremely weak

### ISSUE THREAD

**Issue by zhouxin627** [smartdevicelink/sdl_java_suite#1260] opened 2020-01-28 01:35 UTC
### Bug Report
Crash when video streaming is started about 10 minutes if the WiFi signal is extremely weak.

##### Preconditions
The WiFi signal is extremely weak.

##### Reproduction Steps
1. Connect the head unit to the phone via BT+WiFi
2. Register a NaviAPP
3. Activate a NaviAPP
4. Start video streaming
5. After about 10 minutes

##### Expected Behavior
A crash will not occur

##### Observed Behavior
A crash occurs, all the connected apps are disconnected.

①The data of video streaming and audio streaming is saved into `MultiplexTcpTransport.WriterThread's packetQueue`
then is sent to HU via TCP. This queue's default size is 0x7fffffff

```
        public void write(byte[] msgBytes, int offset, int count) {
            if ((msgBytes == null) || (msgBytes.length == 0)) {
                logInfo("TCPTransport.sendBytesOverTransport: nothing to send");
                return;
            }

            if (offset + count > msgBytes.length) {
                count = msgBytes.length - offset;
            }
            packetQueue.add(new OutPacket(msgBytes, offset, count));

        }
```

②There is no limit to the size of the packetQueue，so the app can save streaming data into the queue without limit.
```
        public void run() {
            while(!isHalted){
                try{
                    OutPacket packet = packetQueue.take();
                    if(packet == null){
                        continue;
                    }

                    OutputStream out;
                    synchronized (MultiplexTcpTransport.this) {
                        out = mOutputStream;
                    }

                    if ((out != null) && (!isHalted)) {
                        try {
                            out.write(packet.bytes, packet.offset, packet.count);
                            if (mVerbose) {
                                logInfo("TCPTransport.sendBytesOverTransport: successfully sent data");
                            }
                        } catch (IOException e) {
                            logError("TCPTransport.sendBytesOverTransport: error during sending data: " + e.getMessage());
                        }
                    } else {
                        if (isHalted) {
                            logError("TCPTransport: sendBytesOverTransport request accepted, thread is cancelled");
                        } else {
                            logError("TCPTransport: sendBytesOverTransport request accepted, but output stream is null");
                        }
                    }

                }catch(InterruptedException e){
                    break;
                }
            }
        }
```

③packetQueue' data can't be sent to HU via TCP immediately when the WiFi signal is extremely weak, so sdlRouterservice crash happens as OOM due to queue increases.

##### OS & Version Information
* Android Version: Android 9
* SDL Android Version: 4.10.1
* Testing Against: SDL Core 6.0.1 + HMI running on our development environment.

##### Occurrence
100%

##### Recovery Method
Kill the NaviAPP, connect BT+WIFI, restart the NaviAPP

##### Log
[log.txt](https://github.com/smartdevicelink/sdl_java_suite/files/4120225/log.txt)

**Comment by JulianKast** [comment] 2020-03-04 15:14
@zhouxin627 Could you provide reproduction steps in how to replicate the issue? How did you simulate a weak wifi signal?

**Comment by zhouxin627** [comment] 2020-03-05 07:05
Hi @JulianKast, there are two ways to simulate it:
1. Increase the distance from WiFi AP to reduce the signal strength of the WiFi connection.
2. Send a large number of `audiostreaming` data continuously to occupy WiFi bandwidth

As long as the data can not be sent out in time, data accumulation occurs.

**Comment by theresalech** [comment] 2020-04-01 15:12
During the 2020-03-31 Steering Committee meeting, the committee voted to close this issue as "won't fix."  This is because the issue is seen as a rare corner case, unlikely to be encountered in production, and a potential fix would increase technical debt in comparison with the likelihood of the issue.

**Closed by theresalech** 2020-04-01 15:12 UTC
