### ISSUE TITLE
Sometimes proxy will not reconnect when it gets the "sdl.router.startservice" broadcast from the router, possible race condition

### ISSUE THREAD

**Issue by jthrun** [smartdevicelink/sdl_java_suite#586] opened 2017-08-15 20:18 UTC
I have found a situation when the Proxy

- did not cycle or stop from an earlier BT disconnect
- receives the "sdl.router.startservice" from the same router (but different instance)
- does not connect because the MultiplexTransport's internal state is "not connected" and "not disconnecting"

It seems to happen at this line in SdlConnection.forceHardwareConnectEvent():

https://github.com/smartdevicelink/sdl_android/blob/5f7da95bb84ba85f388929d66f7eb2efd7f1d368/sdl_android/src/main/java/com/smartdevicelink/SdlConnection/SdlConnection.java#L532-L533

I see it most often when there are many (50+) SDL apps installed on the phone but I don't have solid repro steps.

**Comment by E-SAITO-TMC** [comment] 2020-04-17 08:25
@joeygrover -san @theresalech -san This issue is a top priority for Toyota. 
>I see it most often when there are many (50+) SDL apps installed on the phone but I don't have solid repro steps.

I understood this issue don't have solid reproduction steps. I would like know if it will be reproduced in the latest version.

**Comment by E-SAITO-TMC** [comment] 2020-04-22 01:05
@joeygrover -san We tried it about 50 times and couldn't reproduce it. Would you like to leave this bug open?

**Comment by theresalech** [comment] 2020-04-22 15:59
@jthrun can you please advise if you are still seeing this issue, or if this can be closed?

**Comment by jthrun** [comment] 2020-04-24 18:04
I'm sorry Theresa, I haven't been involved in the SDL related projects for several months now, so I can't say if this is happening in the latest builds or not.

**Comment by theresalech** [comment] 2020-04-27 15:54
Closing as not reproducible.

**Closed by theresalech** 2020-04-27 15:54 UTC
