### ISSUE TITLE
SdlManager.dispose() of sdl_java_suite is not working.

### ISSUE THREAD

**Issue by appinfoindia** [smartdevicelink/sdl_java_suite#1178] opened 2019-09-23 09:49 UTC
[Question]
Even if SdlManager.dispose () was executed, the app registration could not be canceled.
Please tell us how to cancel the app registration on the H/U side in cases other than the following:
- Termination of the app process
- Disconnect of Bluetooth
- Discoonect of USB

[What we tried]
1. Created an app for testing, and made the SDL connection to Emulator
2. Executed SdlManager.dispose() from the app for testing
[Result]
The app was not deregistered and the app remains on the H/U side.

##### OS & Version Information
* Android Version: Android 9
* SDL Android Version: 4.9.1

**Comment by BrettyWhite** [comment] 2019-09-23 13:23
Duplicate of #1172 and fixed with #1176

**Closed by BrettyWhite** 2019-09-23 13:23 UTC
