### ISSUE TITLE
Non-stop notifications cycling after connecting to 2019 Rav4

### ISSUE THREAD

**Issue by MichaelCrimando** [smartdevicelink/sdl_java_suite#1267] opened 2020-02-06 14:34 UTC
### Bug Report
Non-stop notifications cycling after connecting to 2019 Rav4

#### Preconditions
1. Pair Android device via BT to the Rav4
2. Make sure all apps are logged in and permissions enabled on the phone. You do not need to login to the apps in Entune 3.0

##### Reproduction Steps
1. Restart the phone
2. Launch Toyota Entune 3.0 App Suite Connect on the phone
3. Turn on the car and press the Apps button. Ensure that apps show up and are connected.
7. Turn off the car and ensure the device disconnects from BT

##### Expected Behavior
No SDL notifications would be seen

##### Observed Behavior
**Constant notifications:**
Toyota Entune (with Toyota logo) "Ready to connect to your vehicle, Tap to launch"
Toyota Entune  (with SDL logo) "SmartDeviceLink Connected to"  (This is not a typo, it just cuts off)
Toyota+Alexa (with Alexa logo) "Toyota+Alexa is running"
Ford+Alexa (with Alexa logo) "Ford+Alexa is running"

**Notifications that keep coming back every ~10 seconds. Each one has a timer that starts at 00:00 and counts down to -00:05 then disappears:**
Toyota+Alexa (with SDL Logo) "SmartDeviceLink Waiting for connection..."

##### OS & Version Information
- Google Pixel 2 XL
- Android 10
- 2019 Rav4

**SDL Apps:**
- Ford+Alexa 1.0.17
- Pandora 2001.2
- Toyota Entune 3.0 App Suite Connect 1.1.9
- Toyota+Alexa 1.0.8

This has happened 3/3 times tried

**Comment by MichaelCrimando** [comment] 2020-02-06 14:37
Here's a video:
[Non-stop Notifications.zip](https://github.com/smartdevicelink/sdl_java_suite/files/4165592/Non-stop.Notifications.zip)

**Comment by MichaelCrimando** [comment] 2020-02-06 14:39
@kshala-ford @mrapitis 
I made a ticket for the issue that I saw in Toyota systems, since I know you're starting to look at Android notifications and this is one of the pieces of that puzzle

**Comment by joeygrover** [comment] 2020-02-06 15:06
Is it possible you narrow down the apps a little bit? This list is very long and it would be good to understand if it's a bad actor or not. Also can you confirm all of these apps have been SDL certified?

**Comment by MichaelCrimando** [comment] 2020-02-06 15:08
@joeygrover working with @bilal-alsharifi now to simplify and get logs. All the apps I have are from the play store, how can we figure out if they're officially SDL certified?

**Comment by joeygrover** [comment] 2020-02-06 15:34
You can use your OEMs page to view app partners that are available. Looking through our records only Webex Meet and Ford+Alexa are currently certified.

**Comment by MichaelCrimando** [comment] 2020-02-06 18:52
Drastically cut down on apps required to do the test

**Comment by MichaelCrimando** [comment] 2020-02-06 19:40
Logcat logs,
[logcat_02-06-2020_14-23-35.txt](https://github.com/smartdevicelink/sdl_java_suite/files/4167387/logcat_02-06-2020_14-23-35.txt)

**Comment by bilal-alsharifi** [comment] 2020-02-06 20:21
Most of the apps that are used to reproduce the steps use old versions of sdl that have some issues related to the router service:
Pandora uses `4.6.3`
Toyota Entune: `4.7.2`
Toyota+Alexa: `4.7.2`

These issues were fixed in later versions of sdl.

**Comment by bilal-alsharifi** [comment] 2020-02-11 00:26
After testing with @MichaelCrimando, we couldn't reproduce the issue on our Pixel 2XL or Pixel 3XL. The issue is only reproducible currently on @MichaelCrimando Pixel 2XL phone. Is it possible that other apps installed on that phone are affecting the result?

**Comment by MichaelCrimando** [comment] 2020-02-11 12:55
@bilal-alsharifi possibly, but I have 110 apps on my phone. I think we just gotta go based on logs at this point

**Comment by bilal-alsharifi** [comment] 2020-02-11 17:04
It looks like the issue is happening on some Android devices because Android takes some extra time (~5 seconds) to dismiss the router service notification after calling `this.stopForeground(true)`:
https://github.com/smartdevicelink/sdl_java_suite/blob/797b7a14a7fd67fdf6faa504865e4e22228858ef/android/sdl_android/src/main/java/com/smartdevicelink/transport/SdlRouterService.java#L1518

**Closed** 2020-02-24 15:56 UTC
