### ISSUE TITLE
StackOverFlow occurs when SDL service is stopped during use of AudioStreaming

### ISSUE THREAD

**Issue by Yuki-Shoda-Nexty** [smartdevicelink/sdl_java_suite#1292] opened 2020-03-02 07:44 UTC
### Bug Report
StackOverFlow rarely occurs when the SDL service is stopped (for example, due to disconnection from the HU or termination of application on the HS side) during use of AudioStreaming.

##### Prerequisites
Make SDL connection between HU and Android device via USB

##### Reproduction Steps
1.Start the application from the application list screen of the OBE.
   (Call AudioStreamManager # start () / startAudioStream () at time of HMI_FULL)
2.Disconnect the USB.

##### Expected Behavior
StackOverFlow should NOT occur when the SDL service is stopped (for example, due to disconnection from the HU or termination of application on the HS side) during use of AudioStreaming.

##### OS & Version Information
* SDL Android Version:4.7.2

##### Expanded Information
1) ISdlServiceListener.onServiceEnded () is called in SDL disconnection sequence
2) session.stopAudioStream () is called in ISdlServiceListener.onServiceEnded ().
3) ISdlServiceListener.onServiceEnded () is called in session.stopAudioStream ().
4) After  that, 2) and 3) continues to loop over and over again
5) Finally, StackOverflowError occurs.
—
onServiceEnded () is called in stopAudioStream () as stop notification, and stopAudioStream () is called in onServiceEnded ().
Therefore, these functions call each other repeatedly.
Finally, StackOverflowError occurs.

**Comment by JulianKast** [comment] 2020-03-10 14:22
Hi @Yuki-Shoda, I am having trouble replicating this error. Can you test this on SDL version 4.10.1?

**Comment by Yuki-Shoda** [comment] 2020-03-18 02:14
Hi @JulianKast -san,
Yes, we can test this with version 4.10.1. 
Could you tell me the details on how you are having trouble with replicating the error?

**Comment by JulianKast** [comment] 2020-03-23 13:15
@Yuki-Shoda, After starting audio streaming, I've tried killing the app and disconnecting the app from the HU, neither seems to give a StackOverFlowError

**Comment by Yuki-Shoda-Nexty** [comment] 2020-04-28 08:56
@JulianKast -san,As a result of checking with 4.10.1, it did not reproduce even in the environment that we are using.
Are there any other relevant fixes as to why this issue is not reproducible?

**Comment by JulianKast** [comment] 2020-05-13 13:54
@Yuki-Shoda-Nexty , It is always recommended to use the latest release of SDL as there have been 7 releases since 4.7.2. Since the issue is not reproducible in the current library we are closing the issue.

**Closed by JulianKast** 2020-05-13 13:54 UTC
Labels: bug, manager-streaming-audio

**Comment by Yuki-Shoda-Nexty** [comment] 2020-05-15 00:56
@JulianKast -san
Does that mean that there are no 7 related fixes to this issue, instead there have been 7 SDKs released since 4.7.2? Does any of them has fixed the issue?

**Comment by JulianKast** [comment] 2020-05-15 01:04
@Yuki-Shoda-Nexty There was no issue in 4.7.2 that I could see. In your expanded information, Step 3: "ISdlServiceListener.onServiceEnded () is called in session.stopAudioStream ()" is not true. Also, we can't go back and fix old version of SDL, So if you can't replicate the issue in the current release then there is nothing that we can do.
