### ISSUE TITLE
SDL enabled when android device is connected to bluetooth headphones

### ISSUE THREAD

**Issue by ashwink11** [smartdevicelink/sdl_java_suite#1185] opened 2019-10-01 13:14 UTC
# Bug Report
SDL enabled called when connected to a non-SDL Bluetooth device. The issue is seen with Powerbeats, UE Boom 2, Bose QC35

##### Reproduction Steps
1. Connect android device to mentioned Bluetooth device
2. The issue is not 100% reproducible. Retry if not visible. 

##### Expected Behavior
SDL notifications should not be shown when android is connected to the mentioned Bluetooth device.

##### Observed Behavior
SDL notifications should are shown 

##### OS & Version Information
* Android Version: 9
* SDL Android Version: 4.9.1
* Testing Against: Non SDL bluetooth devices

##### Test Case, Sample Code, and / or Example App
NA
[sdlLogs.txt](https://github.com/smartdevicelink/sdl_java_suite/files/3676327/sdlLogs.txt)

**Comment by joeygrover** [comment] 2019-10-01 13:44
Please try to provide detailed reproduction steps. It is much more likely issues can be found and resolved if they are provided. Vague/generalized steps are not helpful.

The implementation is likely incorrect, it is entering legacy mode before the router service actually makes a connection. Make sure they are using the latest officially released library and have followed the guides exactly.

**Comment by joeygrover** [comment] 2019-10-01 15:30
`onSdlEnabled` is only called in two spots. First, when there is a USB connection intent (the old way) seen [here](https://github.com/smartdevicelink/sdl_java_suite/blob/master/android/sdl_android/src/main/java/com/smartdevicelink/transport/SdlBroadcastReceiver.java#L113). The second and most common way is when the intent with action `sdl.router.startservice` is received and a trusted router list downloaded seen [here](https://github.com/smartdevicelink/sdl_java_suite/blob/master/android/sdl_android/src/main/java/com/smartdevicelink/transport/SdlBroadcastReceiver.java#L179).

That intent action is only sent out for a few events.

1. During a transport connection event int the router service seen [here](https://github.com/smartdevicelink/sdl_java_suite/blob/master/android/sdl_android/src/main/java/com/smartdevicelink/transport/SdlRouterService.java#L1671) 
2. When the router service has a transport connect and is sending out pings to ensure client apps are connecting seen [here](https://github.com/smartdevicelink/sdl_java_suite/blob/master/android/sdl_android/src/main/java/com/smartdevicelink/transport/SdlRouterService.java#L2736) and the check for a transport and request to ping seen  [here](https://github.com/smartdevicelink/sdl_java_suite/blob/master/android/sdl_android/src/main/java/com/smartdevicelink/transport/SdlRouterService.java#L797)
3. A router service needs to be started when bluetooth connects seen [here](https://github.com/smartdevicelink/sdl_java_suite/blob/master/android/sdl_android/src/main/java/com/smartdevicelink/transport/SdlBroadcastReceiver.java#L433). This is where the issue would be if there was an issue, however you can clearly see the if statement that prevents the `onSdlEnabled` call seen [here](https://github.com/smartdevicelink/sdl_java_suite/blob/master/android/sdl_android/src/main/java/com/smartdevicelink/transport/SdlBroadcastReceiver.java#L159). Since the intent sent from the first link does not contain the `TransportConstants.START_ROUTER_SERVICE_SDL_ENABLED_EXTRA` ti will fall to the next else if statement. This check will return true because it does have the extra `TransportConstants.PING_ROUTER_SERVICE_EXTRA` and the value is `true`

So as we see the code does not provide a path to `onSdlEnabled` to be called unless the condition of a primary transport being connected in the router service is met. Based on the provided logs we see that the `onSdlEnabled` callback was executed before the router service was started.

![sdlLogs_txt](https://user-images.githubusercontent.com/6579474/65976869-db4ef180-e43e-11e9-94d2-0287ce3cc9f4.png)


With all this in mind, it leads me to believe there is something required in the specific integration that is leading to the issue. Please ensure the app developer is using an officially released and latest version of the SDL library and has followed the guides exactly.

**Comment by ashwink11** [comment] 2019-10-04 11:36
Thank you for detailed analysis. 
Will it be possible for you to try one more time? Unfortunately, I am not able to check on the mentioned headphones yet. 

The issue is visible by force stopping the app when it's connected to headphones and then reopening the app on the phone.
Info I received:

> One way we managed to get the receiver to call onReceive and then onSdlEnabled is by force stopping the app while it's connected to headphones and then opening it.
> The issue is reproducible on many bluetooth devices we tried (UE Boom 2, Bose QC35, etc...) but it does not always happen.

**Comment by joeygrover** [comment] 2019-10-04 15:46
I have tested with the provided steps and different bluetooth devices as requested. I have performed the tests many times, force closing the app, re-opening it, disconnecting the BT device, connecting it, numerous combinations of the previous steps. The results have never shown this issue. There is something specific to this apps integration that is causing the issue. If you can send me the APK through email I will retest with the app, but as for now this issue is not reproducible in the library.

**Comment by joeygrover** [comment] 2019-10-14 15:38
I'm going to close this issue as not reproducible and no follow up has been received.

**Closed by joeygrover** 2019-10-14 15:38 UTC
