### ISSUE TITLE
ScreenManager broken if JSON data is invalid

### ISSUE THREAD

**Issue by kshala-ford** [smartdevicelink/sdl_java_suite#1523] opened 2020-10-05 15:00 UTC
### Bug Report
On a specific Ford SYNC IVI we have seen that the system is returning invalid JSON data to media apps if they change templates. Once they change back to the MEDIA template it looks like sending text is not possible anymore. The app shows an error in the logs where the library catches an NPE caused by this line of code https://github.com/smartdevicelink/sdl_java_suite/blob/4.12.0/base/src/main/java/com/smartdevicelink/managers/ManagerUtility.java#L77 The error message is

> java.lang.NullPointerException: Attempt to invoke virtual method 'int com.smartdevicelink.proxy.rpc.enums.TextFieldName.ordinal()' on a null object reference

The root cause is based on invalid JSON data in the `.name` parameter of a `TextField`. That'll cause `ordinal()` to fail.

#### Suggested fix

While we attempt to fix the issue in the head unit there is need for a library workaround. The easiest is to skip `TextField` objects where `getName()` returns null. However, that skipped field could be `mainField4` which would be skipped, therefore the method would return 3 but it's an unusable result. In this unfortunate situation of a null name, we would suggest to return 4 and write a warning to the logs.

##### Reproduction Steps
1. Use a test media app with 4.12 (or even 4.11)
2. Connect the test app to the concerning IVI
3. Show some text using screen manager
3. SetDisplayLayout `TILES_WITH_GRAPHIC`
4. Show some other text using screen manager

##### Expected Behavior
The new text should be shown

##### Observed Behavior
- Nothing's happening
- The error message is shown in the app logs

##### OS & Version Information
* Android Version: Any (not relevant)
* SDL Android Version: 4.11 or 4.12
* Testing Against: Test app, SYNC3 lite

##### Test Case, Sample Code, and / or Example App
Available on request

**Comment by joeygrover** [comment] 2020-10-05 15:43
Closing as duplicate of #1465 as well as already fixed with two PRs #1474 & #1498.

The behavior desired on this issue as requested by the reporter would result in a poorer UX for scenarios outside the specific case defined. The 3 lines vs 4 lines does not create an unusable result as the reporter states; it creates a less than perfect result that still works. However, if the library took `null` as an assumption that 4 lines of text are available even if we have only received up to `mainField3` we have no confirmation that 4 lines of texts are available. If only 3 lines were available on the IVI system this would result in an unusable UX as the library assumes 4 lines when only 3 are available.

So while it would be a best case solution for a specific scenario where the RPC spec is not followed, it would create extremely poor and unusable UX for other scenarios.

**Closed by joeygrover** 2020-10-05 15:43 UTC

**Comment by kshala-ford** [comment] 2020-10-06 07:30
@joeygrover thank you for sharing the links. I focused on previous releases and didn't take a closer look to develop.

To my understanding mainField4 isn't missing on our system but regarding your response I must say it's wrong. The computed result is unusable because you can't know if mainFields are missing therefore the method can't promise knowledge of maximum number of text fields. `null` is not an assumption of four lines but affects confidence to the result; with `null` and `mainField3` you don't have 100% confirmation that only 3 lines are available. Hence, on systems where 4 lines would be available your implementation behaves inconsistently.

It is up to you to decide which side you want to support. Defending the decision you made is one thing. Affecting application behavior is another.

**Comment by joeygrover** [comment] 2020-10-06 18:41
The logic in the library is written with the assumption that the IVI system properly supplies its capabilities and that it follows the RPC spec. If that system doesn’t adhere to those requirements, it will have to bear the consequences. Null is not an acceptable value and should be ignored in the case where other fields have been processed successfully.

The scenario you stated is statistically improbable. The IVI system was able to successfully create and send a `TextField` item with name `mainfield3` but was not able to do so for `mainfiled4` while still being able to form a proper JSON object. This would only really be possible if the IVI system improperly described their capabilities which is not something the library should protect for.

The situation you are actually seeing is where the IVI system sends a value for `TextFieldName` that is not an accepted/valid value of the RPC spec enum. So the JSON object is properly formed with an incorrect value. This situation demonstrates why an incorrect value should not be the reason to consider an RPC as unusable. Take SDL Core for example, it simply strips out values it doesn’t know about to process what it can, that same logic can be applied here.

If any SDLC member has an IVI system that is demonstrating the behavior you stated it can be discussed further. However, creating a workaround solution for a hypothetical problem is not the best course of action, nor is creating one that, as previously stated, would create an unusable UX as compared to a less than perfect one.

**Comment by kshala-ford** [comment] 2020-10-08 10:29
I think you don't really understand my point that the computed data has no 100% confidence because it knows some data is wrong/corrupted. Specifically to text fields and capabilities the use case is that the head unit returns which fields are visible with the currently selected template. Any other field can be send but will not be presented. That's what the library logic is trying to prevent. Sending more content has no affect to the result. A head unit which would show more content than described in capabilities is more questionable than a bug producing null in the list.

I'm surprised about your arguments not comparing both sides and weigh objectively. It's obvious that you want to defend the decisions you have made in the past but should accept feedback if these decisions are weak in certain scenarios.

**Comment by joeygrover** [comment] 2020-10-08 15:52
Feedback is always welcomed and encouraged. It can be easy to review code ad hoc and not realize how it works within the larger system. This is especially true when trying to handle errors. The logic of how to handle the situation with this issue was thought through properly to give the best average case experience.

I think there is a misunderstanding of what this method is used for and how changing it would impact what's seen on screen. Let's take the example of a developer setting 4 lines of text through the screen manager as follows:

- **Line 1**: Hi
- **Line 2**: my name
- **Line 3**: is
- **Line 4**: SDL

Now let's take a look at how that would appear in the different scenarios  we've discussed.

1\. Best case scenario: Text fields are properly described!

**TextFields**:[mainfield1, mainfield2, mainfield3, mainfield4]

- **mainfield1**: Hi
- **mainfield2**: my name
- **mainfield3**: is
- **mainfield4**: SDL

Looks exactly as expected.

2\. Next let's look at what would happen with null or unsupported values while the HMI actually supported all 4 main fields. as the logic stands today.

**TextFields**:[mainfield1, mainfield2, notificationText, null]

- **mainfield1**: Hi - my name
- **mainfield2**: is - SDL
- **mainfield3**: 
- **mainfield4**:

As you can see, the developer still gets all the information on screen in this scenario. Since we were confident that at least main fields 1 and 2 were available we used those to display all of the information. Obviously this isn't the best case scenario for this HMI, but with either improperly describing HMI capabilities, not following the RPC spec, or having JSON data being corrupted this is an acceptable experience.

3\. When we look at what happens if the HMI truly only supports 2 lines but also includes null or unsupported values.

**TextFields**:[mainfield1, mainfield2, notificationText, null]

- **mainfield1**: Hi - my name
- **mainfield2**: is - SDL

This is the same outcome as if the array only included mainfield1 & mainfield2 which is correct.

4\. Finally let's take look at what would happen in scenario 3 but changing the logic to throw out the textfield array since a null or incorrect value was present.

**TextFields**:[mainfield1, mainfield2, notificationText, null]

- **mainfield1**: Hi
- **mainfield2**: my name

As you can see not all of the information is passed to the HMI and is very likely to create an unusable experience for the user. While the example text given is very trivial, things like turn-by-turn instructions or possibly weather updates would fill out all 4 lines and without combining those lines the user would miss potentially vital information.

In conclusion, the logic does not prevent information from being sent to the HMI, it is actually the exact opposite. The logic in this particularly method ensures that the developer is able to get all main field lines displayed regardless of quantity supported (or assumed supported). One final case to be aware of is that if the capabilities as a whole are null, which is a much more likely scenario in the case the JSON payload is corrupted, the library defaults to 4 lines. If you have any evidence of a JSON object being corrupted in the specific way that it is still able to be formed into a JSON object but only values within that object are affected to the point they can't be recognized as subsequent JSON objects, I would be very eager to find out what's causing that and how we can mitigate that issue.
